# Generated by Django 6.1 on 2026-09-07 09:00

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='username')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=10), django.core.validators.MaxLengthValidator(limit_value=10)], verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('user_type', models.CharField(choices=[('SUPER ADMIN', 'Super Admin'), ('STAFF', 'Staff'), ('Student Admin', 'Student Admin'), ('Student Name', 'Student Name'), ('Student Department', 'Student Department'), ('Student Email', 'Student Email')], default='Student Name', max_length=50, verbose_name='user type')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is staff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
