# Generated by Django 6.1 on 2026-08-26 09:10

import django.db.models.deletion
from django.db import migrations, models


def create_unassigned_department(apps, schema_editor):
    Department = apps.get_model("student", "Department")
    Department.objects.get_or_create(
        id=1,
        defaults={"name": "Unassigned"},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RunPython(
            create_unassigned_department,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.department'),
            preserve_default=False,
        ),
    ]
